FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    ansible \
    python3 \
    python3-pip \
    ssh \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Generate SSH key for ansible
RUN ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N ""

WORKDIR /ansible
CMD ["tail", "-f", "/dev/null"]
